version: '3.2'

services:
  app:
    build: .docker/php/
    container_name: contact_control_app
    entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/var/www
    networks:
      - contact_control
    depends_on:
      - db
  nginx:
    build: .docker/nginx
    container_name: contact_control_nginx
    ports:
      - '80:80'
    volumes:
      - .:/var/www
    networks:
      - contact_control
    depends_on:
      - app
  db:
    build: .docker/db
    container_name: contact_control_db
    ports:
      - '3306:3306'
    volumes:
      - .docker/db/dbdata:/var/lib/mysql
      - .docker/db/scripts:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_ROOT_PASSWORD=root

networks:
  contact_control:
    driver: bridge